os: osx
language: objective-c
matrix:
  include:
    - {osx_image: xcode8.3, env: 'PLAT=macOS   SWFT=3.1 DST="arch=x86_64"'}
    - {osx_image: xcode8.3, env: 'PLAT=iOS     SWFT=3.1 DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode8.3, env: 'PLAT=tvOS    SWFT=3.1 DST="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode8.3, env: 'PLAT=watchOS SWFT=3.1 DST="OS=3.2,name=Apple Watch - 38mm"'}

    - {osx_image: xcode9.2, env: 'PLAT=macOS   SWFT=3.2 DST="arch=x86_64"'}
    - {osx_image: xcode9.2, env: 'PLAT=iOS     SWFT=3.2 DST="OS=11.2,name=iPhone SE"'}
    - {osx_image: xcode9.2, env: 'PLAT=tvOS    SWFT=3.2 DST="OS=11.2,name=Apple TV"'}
    - {osx_image: xcode9.2, env: 'PLAT=watchOS SWFT=3.2 DST="OS=4.2,name=Apple Watch - 38mm"'}

    - {osx_image: xcode9.2, env: 'PLAT=macOS   SWFT=4.0 DST="arch=x86_64"'}
    - {osx_image: xcode9.2, env: 'PLAT=iOS     SWFT=4.0 DST="OS=11.2,name=iPhone SE"'}
    - {osx_image: xcode9.2, env: 'PLAT=tvOS    SWFT=4.0 DST="OS=11.2,name=Apple TV"'}
    - {osx_image: xcode9.2, env: 'PLAT=watchOS SWFT=4.0 DST="OS=4.2,name=Apple Watch - 38mm"'}
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT --verbose
install:
  - xcodebuild -scheme PMKAlamofire -quiet -destination "$DST" SWIFT_VERSION=$SWFT build
script:
  - if [ "$PLAT" != "watchOS" ]; then
      xcodebuild -scheme PMKAlamofire -quiet -destination "$DST" test;
    fi
